name: Deploy to Kubernetes

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker image
        run: |
          docker login --username cuccurese2010 --password ${{ secrets.GH_PAT }} ghcr.io
          docker build --file ${GITHUB_WORKSPACE}/Dockerfile --tag ghcr.io/cuccurese2010/test:latest ${GITHUB_WORKSPACE}
          docker push ghcr.io/cuccurese2010/test:latest


       - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config
          kubectl config set-cluster kubernetes --server=https://d4ea-76-77-137-195.ngrok-free.app

      - name: Deploy to Kubernetes
        run: |
          kubectl --insecure-skip-tls-verify apply -f ./deployment.yaml --validate=false
          kubectl --insecure-skip-tls-verify set image deployment/test test=ghcr.io/cuccurese2010/test:latest --validate=false
