name: Test Kubernetes Connection

on:
  push:
    branches:
      - main

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create kube directory
        run: |
          mkdir -p ~/.kube

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode | sed "s|server: .*|server: https://d4ea-76-77-137-195.ngrok-free.app|" > ~/.kube/config

      - name: Test Kubernetes Connection
        run: |
          kubectl --insecure-skip-tls-verify get pods
