name: Test Kubernetes Connection

on:
  workflow_dispatch:  # Permette di avviare manualmente il workflow
  push:
    paths:
      - '.github/workflows/connection.yml' 
    branches:
      - Connection  # Attiva solo se si fa push su questo ramo

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create kubeconfig
        run: |
         mkdir ${HOME}/.kube
         echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ${HOME}/.kube/config
         cat ${HOME}/.kube/config

      - name: Test Kubernetes Connection
        run: |
          kubectl --insecure-skip-tls-verify get pods
