name: Deploy to Kubernetes

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/my-app:${{ github.sha }} .
        docker push ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      uses: appleboy/k8s-action@v0.1.7
      with:
        kubeconfig: $HOME/.kube/config
        namespace: default
        manifests: |
          ./deployment.yaml
        images: |
          ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}
