name: Test Kubernetes Connection

on:
  push:
    branches: [ main ]

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config
        sed -i "s/https:\/\/d4ea-76-77-137-195.ngrok-free.app/https:\/\/10.0.2.100:6443/g" ~/.kube/config
    - name: Test connection
      run: kubectl get nodes
